FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /chaos-monkey ./cmd/chaos-monkey

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /chaos-monkey /chaos-monkey
ENV DD_SERVICE=aiden-chaos-monkey
ENV DD_ENV=demo
CMD ["/chaos-monkey"]
